# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='line',
            field=models.CharField(max_length=128, null=True, verbose_name='LINE'),
        ),
    ]
